#!/bin/bash
# --------------------------- Settings ----------------------------


# --------------------------- Functions ----------------------------
function install() {
	echo ""
	echo "Install:"
	echo " r  virtualbox"
	echo "    virtualbox-guest-additions-iso"
	if ask ">>>>>>>>>>>>>>>>>>>>> Install it?";
	then
		apt-get install virtualbox virtualbox-guest-additions-iso
	fi
}

function config() {
	echo ""
}